theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Madhur.A.Adsule]
description: [Passionate about turning raw data into patterns, insights, and decisions]
